### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by ZeoWorks** [wawesomeNOGUI/RemoteDesktopForGaming#1]
Hi, this looks very promising.
however, when I try to open the stream in browser (via localhost or public ip address), it simply says "404 page not found".
Any thoughts?
Thanks.

**Comment by wawesomeNOGUI** [comment]
Hi! Do you have the folder “public” in the same directory as main.exe? e.g:
RemoteDesktop-
|  main.exe
|  public-
|  |  index.html

**Comment by ZeoWorks** [comment]
Thank you for getting in touch!
I was actually using "go run screenGrabWebRTC.go" in CMD.
Do I need to compile to get the main.exe?

What is the command line to do so?
Thanks for you help. :)

**Comment by wawesomeNOGUI** [comment]
No problem! Hmmm I actually never tried running with go run:D Compiling to a static binary is worth a try, run the command: go build screenGrabWebRTC.go

**Comment by ZeoWorks** [comment]
Thanks! I get this error, Am I missing something?
```
C:\Users\x\Documents\RemoteDesktopForGaming-1.2>go build screenGrabWebRTC.go
screenGrabWebRTC.go:141:2: no required module provides package github.com/gorilla/websocket: go.mod file not found in current directory or any parent directory; see 'go help modules'
screenGrabWebRTC.go:143:2: no required module provides package github.com/pion/mediadevices: go.mod file not found in current directory or any parent directory; see 'go help modules'
screenGrabWebRTC.go:144:2: no required module provides package github.com/pion/mediadevices/examples/internal/signal: go.mod file not found in current directory or any parent directory; see 'go help modules'
screenGrabWebRTC.go:156:2: no required module provides package github.com/pion/mediadevices/pkg/codec/x264: go.mod file not found in current directory or any parent directory; see 'go help modules'
screenGrabWebRTC.go:164:2: no required module provides package github.com/pion/mediadevices/pkg/driver/screen: go.mod file not found in current directory or any parent directory; see 'go help modules'
screenGrabWebRTC.go:147:2: no required module provides package github.com/pion/webrtc/v3: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

Apologies, I've never used go in the past.  Thanks again for your help!

**Comment by wawesomeNOGUI** [comment]
You’re fine, go has a bunch of weird setup to learn about:D I’ll probably add more setup instructions to the README too. So for building the Remote Desktop program you have to have this project’s folder inside your GOPATH e.g. users/ZeoWorks/go/src/github.com/ZeoWorks/
(You’ll have to make the folder called ZeoWorks inside of the github.com folder)
Paste this code repository’s folder into there. Next go into that folder and run: `go mod init github.com/ZeoWorks` and finally run: `go build screenGrabWebRTC.go`

**Comment by ZeoWorks** [comment]
Thank you very much!

I'm scratching my head around this error when attempting to build after following your instructions;
`screenGrabWebRTC.go:141:2: no required module provides package github.com/gorilla/websocket; to add it:
        go get github.com/gorilla/websocket
screenGrabWebRTC.go:143:2: no required module provides package github.com/pion/mediadevices; to add it:
        go get github.com/pion/mediadevices
screenGrabWebRTC.go:144:2: no required module provides package github.com/pion/mediadevices/examples/internal/signal; to add it:
        go get github.com/pion/mediadevices/examples/internal/signal
screenGrabWebRTC.go:156:2: no required module provides package github.com/pion/mediadevices/pkg/codec/x264; to add it:
        go get github.com/pion/mediadevices/pkg/codec/x264
screenGrabWebRTC.go:164:2: no required module provides package github.com/pion/mediadevices/pkg/driver/screen; to add it:
        go get github.com/pion/mediadevices/pkg/driver/screen
screenGrabWebRTC.go:147:2: no required module provides package github.com/pion/webrtc/v3; to add it:
        go get github.com/pion/webrtc/v3
`

Any thoughts?  Thanks again.

**Comment by wawesomeNOGUI** [comment]
Hmmm run: `go env` and check to see if GO111MODULES=on. If not, then run: `set GO111MODULES=on`

**Comment by ZeoWorks** [comment]
Thanks, same issue appears.
Am I missing any downloads? Thus far I've downloaded go1.16.4.windows-amd64.msi
Thanks again

**Comment by wawesomeNOGUI** [comment]
Hmmm yep you’ve got the latest go version which is good👍 This is definitely a hard project to build😰 I’m not entirely sure of the best way to build go programs in general, but running ‘go get’ on everything the error spits out should allow you to build most of it👍 Then you would have to get video encoding up and running which I can help out with too

**Comment by ZeoWorks** [comment]
Thank you, do you think you could email me a pre-compiled exe of this project?
My email address is zeoworks@hotmail.co.uk  We can go from there.
Thanks again for all your help!

**Comment by wawesomeNOGUI** [comment]
Oh yeah that’d work! I’ll send it over
