### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by itroeix** [wawesomeNOGUI/RemoteDesktopForGaming#5]
When I want to compile I get this error:
```
C:\Users\itroeix\Downloads\RemoteDesktopForGaming-1.4.4\RemoteDesktopForGaming-1.4.4>go build screenGrabWebRTC.go
# command-line-arguments
.\screenGrabWebRTC.go:475:13: undefined: screenshot.Setup
.\screenGrabWebRTC.go:476:19: undefined: screenshot.TearDown
```

**Comment by wawesomeNOGUI** [comment]
Ahhh yeah, one library I was dependent on didn't seem to work after they updated it, so I edited their code. So you can either try commenting those lines out, or replace kbinani's screenshot_windows.go in go/pkg with the one I provided in this repository.

**Comment by itroeix** [comment]
Commenting out the lines does not show display, modifying the screenshot_windows.go file in go/pkg still has the same error

**Comment by itroeix** [comment]
I already managed to solve it, when modifying the screenshot_windows.go file with notepad++ it could not be saved since the file was read-only, I used the normal notepad, saved it in another directory and then moved that file to the directory where the package is, thank you so much!

**Comment by wawesomeNOGUI** [comment]
Awesome! Glad it worked 👍
